### PR TITLE
Buildout

### PR DESCRIPTION
**Pull request by jensens**
To help with development in an controlled environment buildout helps at some point. Even if the same can be achieved with naked virtualenv -  buildout makes i more explicit and documented. This is purely optional. 

Remark:
I put this on the main branch maintain/0.6.x - however theres also master and develop. This is quite confusing and there should be a statement somewhere whats the proposed process for development is, esp. which branch to fork. I hope I took the righ one.

### CODE REVIEW

**Comment by htgoebel** [comment]
Closed accidentally by deleting maintain/0.6.x branch. But this is still useful.

**Comment by htgoebel** [comment]
Thanks for this pull-request. As you may know, this project is currently unmaintained, this is why you got now feedback yet.

IMHO this is useful, but I would throw out all off the stuff related to eazy_install & Co. and just go with pip - which did not exist when you created the files.

Hmm, rethinking this: Is there really still a need to have a buildout scripts? Since then pip's requirements files have been born and are widely used. When using buildout, we add quite some pile of code (about 200 lines of code) which basically doe the same but need to be maintained by this project. What do you think?

**Comment by jensens** [comment]
Today I would also use ``virtualenv``, ``pip`` and its  ``requirements.txt``/ ``constraints.txt``.

**Comment by htgoebel** [comment]
Do you want o provide  requirements.txt/ constraints.txt, or shall we just close the pull-request?

**Comment by jensens** [comment]
I think, just close it, if one is in need of pinned versions it's easy to add them using ``pipenv`` or similar.

**Pull request closed without merging**
